remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false



title: "Northern New Mexico Highlights"
description: "An app that will tell you the highlights of places to go see,
 while in or close to a particular city. "
author:
  name: "Layla Coriz,  Nicholas Mitchell, Royce Reano"


  copyright: true  